/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AgileButton {
    'color': 'primary' | 'accent' | 'light';
    'disabled': boolean;
    'shape': 'square' | 'round';
    'size': 'small' | 'default' | 'large';
    'type': 'button' | 'reset' | 'submit';
  }
}

declare global {


  interface HTMLAgileButtonElement extends Components.AgileButton, HTMLStencilElement {}
  var HTMLAgileButtonElement: {
    prototype: HTMLAgileButtonElement;
    new (): HTMLAgileButtonElement;
  };
  interface HTMLElementTagNameMap {
    'agile-button': HTMLAgileButtonElement;
  }
}

declare namespace LocalJSX {
  interface AgileButton extends JSXBase.HTMLAttributes<HTMLAgileButtonElement> {
    'color'?: 'primary' | 'accent' | 'light';
    'disabled'?: boolean;
    'shape'?: 'square' | 'round';
    'size'?: 'small' | 'default' | 'large';
    'type'?: 'button' | 'reset' | 'submit';
  }

  interface IntrinsicElements {
    'agile-button': AgileButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


